apiVersion: kataconfiguration.openshift.io/v1
kind: KataConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  name: default-kata-config
spec:
  enablePeerPods: {{ if or (eq .Values.global.clusterPlatform "Azure") (eq .Values.global.clusterPlatform "AWS") }}true{{ else }}false{{ end }}